version: '3.7'

services:
  database:
    image: mysql/mysql-server:8.0
    volumes:
      - ./database:/var/lib/mysql
    restart: always
    ports:
      - '3320:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
  wordpress:
    depends_on:
      - database
    image: wordpress:latest
    volumes:
      - ./:/var/www/html
      - ./aio-wp:/var/www/html/wp-content/plugins/aio-wp
    restart: always
    ports:
      - '8000:80'
    environment:
      WORDPRESS_DB_HOST: database:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    user: "1000:1000"